<?php

/**
 * hook_wechat_message
 */
function wechatdemo_wechat_message($weObj){
  $type = $weObj->getRev()->getRevType();
  switch($type){
    case Wechat::MSGTYPE_TEXT:
      _wechatdemo_ontext($weObj);
      break;
    case Wechat::MSGTYPE_EVENT:
      _wechatdemo_onevent($weObj);
      break;	  
  }
}

/**
 * demo auto reply to text
 */
function _wechatdemo_ontext($weObj){
  $text = $weObj->getRevContent();
  if($text === 'ping'){
    $weObj->text('pong');
  }
}

/**
 * override menu event
 */
function _wechatdemo_onevent($weObj){
  $event = $weObj->getRevEvent();
  if(!$event){
    return false;
  }
  if($event['event']=='CLICK' && $event['key'] == 'KEY_ABOUT'){
    $out = "这是一个测试Demo\n";
	$wechatid = $weObj->getRevFrom();
	if($wechatid ){
	  $out .= "您的微信openid为 $wechatid \n";
	  $wechatuser=wechat_token_get_user($wechatid);
	  if($wechatuser){
	    $out .= "您的用户ID为 {$wechatuser->uid} \n";
	  }
	  else{
	    $out .= "您还没有与我们网站绑定，请点击右下登录按钮进行测试\n";
	  }
	
	}
    $weObj->text($out);
  }
}

/**
 * hook_menu
 */
function wechatdemo_menu(){
  $items['wechat/auth/base'] = array(
    'title' => 'Wechat Auth',
    'page callback' => 'wechatdemo_auth_base',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  
  $items['wechat/auth/userinfo'] = array(
    'title' => 'Wechat Auth',
    'page callback' => 'wechatdemo_auth_userinfo',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  
  $items['wechat/auth/error'] = array(
    'title' => 'Wechat Auth',
    'page callback' => 'wechatdemo_auth_error',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function wechatdemo_auth_error(){
  return 'on error';
}

function wechatdemo_auth_base(){
  global $user;
  if(user_is_logged_in()){
    return 'you have login '.$user->name;
  }
  wechat_snsapi_base(url('wechat/auth/base', array('absolute'=>true)),url('wechat/auth/error', array('absolute'=>true)));
  return 'good';
}

function wechatdemo_auth_userinfo(){
  global $user;
  if(user_is_logged_in()){
    return 'you have login '.$user->name;
  }
  wechat_snsapi_userinfo(url('wechat/auth/userinfo', array('absolute'=>true)),url('wechat/auth/error', array('absolute'=>true)));
  return 'good';
}